### ISSUE TITLE
Importance of JVM parameters

### ISSUE THREAD

**Issue by Pascal66** [TilmanNeumann/java-math-library#18]
With  "-Xms4g", "-Xmx4g"  Combined 
->SIQS 1 thread:       2732664,400 µs
->PSIQS 7 threads: 2510790,210 µs
Without  
->SIQS 1 thread:       3252015,594 µs
->PSIQS 7 threads: 3249436,100 µs
  
Using 2x 128bits 189527046769670452665699925639138782629 x 145320076287112015128258773072589293279
"27542084895039556995681746820634403757320668248657547717737190830239511650491"

**Comment by Pascal66** [comment]
Before you ask why:
SISQ GC : 
SIQS.testCombined:�gc.count                         2         1  avgt    3           2,000                   counts
SIQS.testCombined:�gc.time                           2         1  avgt    3          38,000                       ms
PSQIQS GC :
SIQS.testCombined:�gc.count                         2         7  avgt    3          55,000                   counts
SIQS.testCombined:�gc.time                          2         7  avgt    3        1312,000                       ms

**Comment by TilmanNeumann** [comment]
When this project was hosted on my homepage, I had a proposition for good JVM parameters. It certainly contained the proposal that Xmin and Xmax should be the same, and more stuff. I did not add that advice here because GC behavior has been changing a lot in the last years, and I'ld have to re-test all options.

**Comment by Pascal66** [comment]
Hello.
I’ve made a java version of a twin prime sieve.
Maybe usefull in your math library ?
PAscal

**Comment by TilmanNeumann** [comment]
Hi Pascal, I would be interested.

**Comment by Pascal66** [comment]
Sorry, missed to give you the link :
[TwinsPrimesSieve](https://github.com/Pascal66/TwinsPrimesSieve)

**Comment by TilmanNeumann** [comment]
This is a pretty fast program.
Two things that didn't work for me:
1. comma-separated inputs like "0, 1000" give a InputMismatchException
2. How do I print _all_ twin primes? Commenting in printprms() does not seem to help...

**Comment by Pascal66** [comment]
Hello,
first it's one comma or one space (you entered both)
Second, i've not really tested with low values
it's more usable for a big range of integers (ie 0,200000000000) or more to count numbers of twins pairs
in this case (0,2e11) this is not acceptable to print 424.084.653 of all :)

**Comment by TilmanNeumann** [comment]
Hi Pascal,
your program looks stable and very fast. I'ld like to put it into my canonical package structure, i.e. somewhere near de.tilman_neumann.jml.primes. Is that ok for you? (I'ld play with it later on, cause right now I have another project)

Btw. I am always a fan of seeing results for small inputs, just for debugging/QA ;-)

**Comment by Pascal66** [comment]
Hello,
I’ve asked Jabari (the mathematician who’s create this sieve) and he’s happy that you put my java code in your package.
I just have to modify some http links of his theory.
I’ve a little modified the debugging part, but due to the structure of the code it’s not very easy and little buggy.
HAvae a nice day
PAscal

**Comment by TilmanNeumann** [comment]
Hi Pascal,
thanks for asking the author.
The program can now be found in package de.tilman_neumann.jml.primes.exact.
Just give me a pull request if you have improvements.
Best wishes
Till
