### ISSUE TITLE
Excess messages for big numbers

### ISSUE THREAD

**Issue by mcguigan228** [TilmanNeumann/java-math-library#27]
Using PSIQS to factor 330 bit numbers seems to bring in SIQS for internal factoring. Problem is the global ANALYZE causes the sub-SIQS stats to be displayed in endless messages. I put in an override in SIQS to get around the problem.

**Comment by TilmanNeumann** [comment]
I was aware of that problem and thought that I'ld had fixed it with my commit 2020-12-26 21:36:12. Since then, SIQS_Small, which has its own ANALYZE flag, should be used inside the TDiv_QS* classes.

**Comment by TilmanNeumann** [comment]
According to my tests the issue is resolved -> close as requested (by email)
