### ISSUE TITLE
[Idea] GPU

### ISSUE THREAD

**Issue by Pascal66** [TilmanNeumann/java-math-library#6]
Can be usefull for opencl gpu
https://www.logicbig.com/tutorials/misc/gpu-programming/aparapi/intro-with-example.html
https://github.com/Syncleus/aparapi

**Comment by TilmanNeumann** [comment]
Looks interesting.

**Comment by TilmanNeumann** [comment]
Uh, are you working as well on such an oldish machine?
The climate will love you for not wasting too many resources ;-))

Btw. sorry I need some time to work through your pull requests. Just noticed the ones you withdrawed. The Montgomery stuff looks quite interesting.

**Comment by Pascal66** [comment]
No more than 45W ! Core-i7-3630QM-2.4Ghz-12Go
I've loose the MontgomeryReduction since my hard rebasing git
I'm retrieving my old improvement i've made before

**Comment by TilmanNeumann** [comment]
> No more than 45W ! Core-i7-3630QM-2.4Ghz-12Go
:-)

> I've loose the MontgomeryReduction since my hard rebasing git
> I'm retrieving my old improvement i've made before

That's a pity, I hope you can recover it!
